# Generated by Django 5.2.5 on 2025-08-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECGFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=50)),
                ('total_records', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('ecg_wave', models.JSONField()),
                ('heart_rate', models.FloatField()),
                ('label', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('untouched', 'Untouched'), ('skipped', 'Skipped'), ('marked', 'Marked'), ('deleted', 'Deleted')], default='untouched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.ecgfile')),
            ],
            options={
                'indexes': [models.Index(fields=['patient_id'], name='api_ecgreco_patient_240830_idx'), models.Index(fields=['status'], name='api_ecgreco_status_527976_idx'), models.Index(fields=['label'], name='api_ecgreco_label_8d24e3_idx')],
            },
        ),
    ]
