# Generated by Django 5.2.5 on 2025-08-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecgfile',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
