# Generated by Django 5.2.5 on 2025-08-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ecgfile_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='ecgrecord',
            new_name='api_ecgreco_label_i_72e21c_idx',
            old_name='api_ecgreco_label_8d24e3_idx',
        ),
        migrations.AlterField(
            model_name='ecgrecord',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ecglabel'),
        ),
    ]
