# Generated by Django 5.2.5 on 2026-02-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ecgrecord_status_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='ai_label',
            field=models.ForeignKey(blank=True, help_text='Label predicted by the AI model. Stored separately from the human label.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_records', to='api.ecglabel'),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='ai_model_name',
            field=models.CharField(blank=True, help_text='Name of the model that produced ai_label.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True means a human has confirmed this label is correct.'),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='labeled_by',
            field=models.CharField(choices=[('import', 'Imported'), ('human', 'Human'), ('ai', 'AI')], default='import', max_length=10),
        ),
        migrations.AlterField(
            model_name='ecgrecord',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='api.ecglabel'),
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['is_verified'], name='api_ecgreco_is_veri_a04eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['ai_label'], name='api_ecgreco_ai_labe_f26ed1_idx'),
        ),
    ]
