# Generated by Django 5.2.5 on 2026-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ecgrecord_ai_label_ecgrecord_ai_model_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='Confidence core (e.g., max probability) for the AI prediction.', null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='ai_probabilities',
            field=models.JSONField(blank=True, help_text='Full probability distribution across all labels.', null=True),
        ),
    ]
