# Generated by Django 5.2.5 on 2026-05-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deployedmodel_patientmodelassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deployedmodel',
            new_name='api_deploye_key_2b494a_idx',
            old_name='api_deploye_key_bfef24_idx',
        ),
        migrations.RenameIndex(
            model_name='deployedmodel',
            new_name='api_deploye_base_mo_1d8dad_idx',
            old_name='api_deploye_base_m_9ae810_idx',
        ),
        migrations.RenameIndex(
            model_name='deployedmodel',
            new_name='api_deploye_source__070c7e_idx',
            old_name='api_deploye_source__f8f7aa_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmodelassignment',
            new_name='api_patient_patient_af5724_idx',
            old_name='api_patien_patient_9b9a34_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='default_plot_library',
            field=models.CharField(default='chartjs', help_text='Default plotting library to use for ECG charts.', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_missing_weights',
            field=models.BooleanField(default=True, help_text='Show models that do not have weights available in the UI.'),
        ),
    ]
