# Generated by Django 5.2.5 on 2026-05-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_settings_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_plot_library',
            field=models.CharField(default='echarts', help_text='Default plotting library to use for ECG charts.', max_length=50),
        ),
    ]
