# Generated by Django 5.2.5 on 2026-05-07 17:49

from django.db import migrations


def update_plot_library(apps, schema_editor):
    Profile = apps.get_model('api', 'Profile')
    Profile.objects.filter(default_plot_library='chartjs').update(default_plot_library='echarts')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_default_plot_library'),
    ]

    operations = [
        migrations.RunPython(update_plot_library),
    ]
